name: Telegram Minute of Silence Bot

on:
  schedule:
    - cron: "0 4 * * *"  # 8:0 0 Київ (6:00 UTC) 
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python test.py