name: Telegram Test Bot

on:
  schedule:
    - cron: "*/2 19-21 * * *"  # кожні 2 хв перед 22:00 Данія
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        run: python test.py